variables:
  BUILD_OUTPUT_DIR: app/build/outputs/apk

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd cliqzSearch
    npm ci
    mkdir -p build
    npm run build
  displayName: 'Build search (debug)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleDebug'
  displayName: 'Assemble Debug'
  
- script: |
    echo "$(sentry_token)" > .sentry_token
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Insert Sentry DSN'

- script: |
    cd cliqzSearch
    npm run build:prod
  displayName: 'Build search (release)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleRelease'
  displayName: 'Assemble Release'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(BUILD_OUTPUT_DIR)/'
    artifactName: apks
  displayName: 'Publish APKs'
